"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.APPCHECK_SETUP_INSTRUCTIONS = exports.APPCHECK_EXAMPLES = void 0;
exports.verifyAppCheck = verifyAppCheck;
exports.withAppCheck = withAppCheck;
exports.isAppCheckEnforced = isAppCheckEnforced;
const functions = __importStar(require("firebase-functions"));
/**
 * App Check Middleware for Firebase Cloud Functions
 *
 * PURPOSE:
 * Protects callable Cloud Functions from abuse by verifying App Check tokens.
 * This prevents bots and unauthorized clients from calling your functions.
 *
 * SECURITY MODEL:
 * - App Check tokens are generated by Firebase SDK on the client
 * - Tokens prove the request comes from your legitimate app
 * - Backend verifies tokens before processing requests
 *
 * USAGE:
 * ```typescript
 * export const myFunction = functions.https.onCall((data, context) => {
 *   // Verify App Check token
 *   verifyAppCheck(context);
 *
 *   // Function logic here...
 * });
 * ```
 *
 * ENFORCEMENT MODES:
 * - Monitor: Log violations but allow requests (for testing)
 * - Enforce: Reject requests without valid App Check tokens
 *
 * @see https://firebase.google.com/docs/app-check
 */
/**
 * Verify App Check token from callable function context
 *
 * @param context - CallableContext from Cloud Function
 * @param options - Verification options
 * @throws HttpsError if token is invalid or missing
 */
function verifyAppCheck(context, options = {}) {
    var _a, _b, _c;
    const { monitorOnly = false, errorMessage } = options;
    // Check if App Check token is present
    if (!context.app) {
        const message = errorMessage || "App Check verification failed: No token provided";
        functions.logger.warn("App Check verification failed", {
            message,
            uid: (_a = context.auth) === null || _a === void 0 ? void 0 : _a.uid,
            timestamp: Date.now(),
        });
        if (!monitorOnly) {
            throw new functions.https.HttpsError("failed-precondition", message);
        }
        return;
    }
    // Token is present and verified by Firebase automatically
    // context.app contains the verified App Check token data
    functions.logger.debug("App Check verified", {
        uid: (_b = context.auth) === null || _b === void 0 ? void 0 : _b.uid,
        appId: (_c = context.app) === null || _c === void 0 ? void 0 : _c.appId,
    });
}
/**
 * Wrapper for callable functions with App Check verification
 *
 * USAGE:
 * ```typescript
 * export const myFunction = withAppCheck(
 *   async (data, context) => {
 *     // Your function logic here
 *     return { success: true };
 *   },
 *   { monitorOnly: false } // Enforce mode
 * );
 * ```
 *
 * @param handler - Your function handler
 * @param options - App Check options
 * @returns Wrapped function with App Check verification
 */
function withAppCheck(handler, options = {}) {
    return functions.https.onCall(async (data, context) => {
        // Verify App Check before executing function
        verifyAppCheck(context, options);
        // Execute the actual function
        return handler(data, context);
    });
}
/**
 * Get App Check enforcement mode from environment
 *
 * Set APPCHECK_ENFORCE=true in environment to enforce
 * Default is monitor mode (log only)
 */
function isAppCheckEnforced() {
    return process.env.APPCHECK_ENFORCE === "true";
}
/**
 * Example usage with different modes
 */
exports.APPCHECK_EXAMPLES = {
    /**
     * Monitor mode: Log violations but allow requests
     * Good for testing and gradual rollout
     */
    monitorMode: `
    export const myFunction = functions.https.onCall((data, context) => {
      verifyAppCheck(context, { monitorOnly: true });
      // Function logic...
    });
  `,
    /**
     * Enforce mode: Reject requests without valid tokens
     * Use in production after testing
     */
    enforceMode: `
    export const myFunction = functions.https.onCall((data, context) => {
      verifyAppCheck(context, { monitorOnly: false });
      // Function logic...
    });
  `,
    /**
     * Using wrapper function
     */
    wrapperMode: `
    export const myFunction = withAppCheck(
      async (data, context) => {
        // Function logic with automatic App Check verification
        return { success: true };
      },
      { monitorOnly: isAppCheckEnforced() }
    );
  `,
};
/**
 * Setup instructions for App Check in Cloud Functions
 */
exports.APPCHECK_SETUP_INSTRUCTIONS = `
Firebase App Check Setup for Cloud Functions:

1. Enable App Check in Firebase Console:
   - Go to Firebase Console > App Check
   - Register your app
   - Enable App Check for Cloud Functions

2. Configure reCAPTCHA v3:
   - Create site key at https://console.cloud.google.com/security/recaptcha
   - Add domains (localhost for dev, your-domain.com for prod)
   - Add site key to client app .env: VITE_RECAPTCHA_SITE_KEY

3. Deploy Functions with App Check:
   - Add verifyAppCheck() to your callable functions
   - Deploy: firebase deploy --only functions
   - Monitor App Check metrics in Firebase Console

4. Enforcement Strategy:
   a. Start with Monitor mode (monitorOnly: true)
   b. Collect metrics for 1-2 weeks
   c. Verify no legitimate traffic is blocked
   d. Switch to Enforce mode (monitorOnly: false)
   e. Set environment variable: APPCHECK_ENFORCE=true

5. Testing:
   - Development: Use debug tokens (VITE_APPCHECK_DEBUG_TOKEN)
   - Staging: Monitor mode with real tokens
   - Production: Enforce mode

6. Monitoring:
   - Check Firebase Console > App Check > Metrics
   - Monitor Cloud Functions logs for App Check warnings
   - Track token rejection rate
`;
//# sourceMappingURL=app-check.js.map